spring.application.name=project-stylus

tmdb.readKey=${TMDB-READ-KEY}
spring.data.redis.url=${REDIS-KEY}
gemini.api.key=${GEMINI-KEY}

spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.zbnpwhtqnmggmrxvbmsp
spring.datasource.password=PAPAmama@2005#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
