spring.application.name=project-stylus

tmdb.readKey=${TMDB-READ-KEY}
spring.data.redis.url=${REDIS-KEY}
gemini.api.key=${GEMINI-KEY}
gemini.api.key.daily=${GEMINI-KEY-DAILY}

spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=${POST-USERNAME}
spring.datasource.password=${POST-PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

upstash.blob.url=https://bd15321a8500.blob.upstash.io
upstash.blob.token=${BLOB-TOKEN}